# -*- coding: utf-8 -*-
"""lab11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AZb0RDTQkyLnlci48YFdneyUjD3xXAw3
"""

#1.Work with built-in modules – calendar, datetime

import calendar
y=2021
m=2
print(calendar.month(y,m))

import calendar
y=2021
print(calendar.calendar(y))

import calendar
y=2021
m=1
w=1
print(calendar.month(y,m,w))

import datetime
print(datetime.datetime.now())

import datetime
x=datetime.datetime.now()
print(x.year)
print(x.strftime("%A"))

import datetime
print(datetime.datetime(2020,5,17))
x=datetime.datetime(2020,10,12)
print(x.strftime("%B"))
print(x.strftime("%d"))
print(x.strftime("%w"))
print(x.strftime("%Y"))
print(x.strftime("%A"))
print(x.strftime("%a"))
print(x.strftime("%H"))

